import numpy as np

class Classifier_svm(object):
    def __init__(self, data):
        '''
            data : training set
            f_vectorizer : filename containing a CountVectorizer,
                None if generated by data
        '''
        self.data = data
        self.f_vectorizer

